<script src={{ asset('js/jquery.min.js') }}></script>
<script src={{ asset('js/bootstrap.js') }}></script>
<script src="{{ asset('js/owl.carousel.min.js') }}"></script>
<script src="{{ asset('js/sweetalert2.all.min.js') }}"></script>
<script src="{{url('//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js')}}"></script>
<script src="{{url('https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('js/datatable.js')}}"></script>
<script src="{{asset('js/select2.js')}}"></script>
<script src="{{asset('js/function.js')}}"></script>
<script src="{{asset('js/external.js')}}"></script>